---
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=kubernetes
after_success:
  coveralls
env:
  TRAVIS_SKIP_SERVER_VERSION: 1
